# permissions for end users to edit virtualrobots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualrobot-editor-role
rules:
- apiGroups:
  - robots.ludusrusso.dev
  resources:
  - virtualrobots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - robots.ludusrusso.dev
  resources:
  - virtualrobots/status
  verbs:
  - get
